CREATE SCHEMA "markman";
--> statement-breakpoint
CREATE TYPE "public"."type" AS ENUM('folder', 'bookmark');--> statement-breakpoint
CREATE TABLE "markman"."bookmarks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "markman"."bookmarks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chromeId" integer NOT NULL,
	"type" "type",
	"isPinned" boolean DEFAULT false,
	"pinOrder" integer,
	"title" varchar(255) NOT NULL,
	"url" varchar(255) NOT NULL,
	"domain" varchar(255),
	"favicon" varchar(255),
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp,
	"parentId" integer NOT NULL,
	"tags" integer[] DEFAULT ARRAY[]::integer[] NOT NULL
);
--> statement-breakpoint
CREATE TABLE "markman"."tags" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "markman"."tags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"color" varchar(255) NOT NULL,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp
);
